### ISSUE TITLE
Lots of exceed maximum number of attempts and fail.

### ISSUE THREAD

**Issue by dgomesbr** [trek10inc/awsets#2]
Steps:
    Running `./awsets list -o all.json` with a custom `AWS_PROFILE` set.

Stack:
```
1: failed job us-west-1 - AWSGreengrassGroup
 with error: failed to list greengrass groups: exceeded maximum number of attempts, 3, TooManyRequestsException: Too Many Requests
	status code: 429, request id: 04eafedd-fdaf-4442-a1c1-113415c22ffc
3: failed job us-west-1 - AWSGreengrassCoreDefinition
 with error: failed to list greengrass core definitions: exceeded maximum number of attempts, 3, TooManyRequestsException: Too Many Requests
	status code: 429, request id: c0bf6a76-77e8-4fbe-a890-61c2801710c1
2: failed job us-west-1 - AWSGreengrassFunctionDefinition
 with error: failed to list greengrass function definitions: exceeded maximum number of attempts, 3, TooManyRequestsException: Too Many Requests
	status code: 429, request id: 688f3272-5b39-41a8-aa6c-c238081bf0e4
6: failed job ap-northeast-3 - AWSEc2TransitGateway
 with error: InvalidAction: The action DescribeTransitGateways is not valid for this web service.
	status code: 400, request id: 01331f76-be70-4a48-a5cc-d4f892b48bc4
2: failed job ap-northeast-3 - AWSCloudFormationStackSet
 with error: ValidationError: AWS CloudFormation StackSets is not supported in this region
	status code: 400, request id: b4041a21-b14f-4a9a-b775-be75c2df9962
7: failed job us-west-1 - AWSGreengrassResourceDefinition
 with error: failed to list greengrass resource definitions: exceeded maximum number of attempts, 3, TooManyRequestsException: Too Many Requests
	status code: 429, request id: 275297d2-96f5-4efa-8aa5-ba5748a35e61
0: failed job ap-northeast-3 - AWSApiGatewayApiKey
 with error: AccessDeniedException:
	status code: 403, request id: d89513e7-db9c-4da9-8796-e2534586e0e5
0: failed job us-west-1 - AWSGreengrassDeviceDefinition
 with error: failed to list greengrass device definitions: exceeded maximum number of attempts, 3, TooManyRequestsException: Too Many Requests
	status code: 429, request id: 614d40e2-a902-4691-9d10-277f674df0a9
5: failed job us-west-1 - AWSGreengrassSubscriptionDefinition
 with error: failed to list greengrass subscription definitions: exceeded maximum number of attempts, 3, TooManyRequestsException: Too Many Requests
	status code: 429, request id: 636d7bd6-51af-4369-8c75-bdbfff9d5960
9: failed job us-west-1 - AWSGreengrassConnectorDefinition
 with error: failed to list greengrass connector definitions: exceeded maximum number of attempts, 3, TooManyRequestsException: Too Many Requests
	status code: 429, request id: d34de1f4-69ba-4ec6-b020-039b2972e769
9: failed job us-west-1 - AWSGreengrassLoggerDefinition
 with error: failed to list greengrass logger definitions: exceeded maximum number of attempts, 3, TooManyRequestsException: Too Many Requests
	status code: 429, request id: f4cdb082-0f2c-4294-9a82-c0aa185e1018
6: failed job ap-northeast-3 - AWSApiGatewayVpcLink
 with error: AccessDeniedException:
	status code: 403, request id: e6bc79c1-2879-4787-b836-f786bb65716e
6: failed job ap-northeast-3 - AWSApiGatewayV2DomainName
 with error: failed to list apigatewayv2 domain names: AccessDeniedException:
	status code: 403, request id: 5c487e09-35bc-4b6d-aed7-01da76ee3128
7: failed job ap-northeast-3 - AWSApiGatewayDomainName
 with error: AccessDeniedException:
	status code: 403, request id: b54f89b7-1409-41ac-b9fb-773b083d6784
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3278f33]

goroutine 41 [running]:
github.com/trek10inc/awsets/arn.ParseP(...)
	/home/runner/work/awsets/awsets/arn/main.go:32
github.com/trek10inc/awsets/lister.AWSEcsCluster.List(0xc00041baa0, 0x9, 0x42d8840, 0xc00023e9c0, 0x42d2ce0, 0xc0004395e0, 0x42d2ae0, 0xc0000f2cc0, 0xc0013be450, 0x2, ...)
	/home/runner/work/awsets/awsets/lister/ecs_cluster.go:80 +0x973
github.com/trek10inc/awsets.List.func1(0xc00003cb40, 0xc000456180, 0xc00043a1c0, 0xc00045e4a0, 0x7, 0xc00053e060)
	/home/runner/work/awsets/awsets/main.go:206 +0x9ba
created by github.com/trek10inc/awsets.List
	/home/runner/work/awsets/awsets/main.go:171 +0x1e7
```

**Comment by jcarter3** [comment]
Thanks for the issue! The latest release should fix this - the nil pointer is the one that kills it. The others are actually "this service is not supported in this region", but each service uses a different error code to communicate that. They should all be suppressed now, but please let me know if you find any others.

**Comment by dgomesbr** [comment]
Thanks @jcarter3, I did had a feel other errors, but did output the `all.json` this time.

```
~/Downloads/awsets_0.2.4_darwin_x86_64$ ./awsets list -o all.json
9: failed job us-east-1 - AWSAmplifyApp
 with error: failed to list branches for app d3jz6wpao4y285: BadRequestException: maxResults must be greater than 0 and less than or equal to 50.
	status code: 400, request id: af6c2051-803a-4cd7-a37a-87e21b1180fa
6: failed job ap-northeast-3 - AWSCloudFormationStackSet
 with error: ValidationError: AWS CloudFormation StackSets is not supported in this region
	status code: 400, request id: cef8ff52-fdc6-45b2-b990-6f60d34c809b
7: failed job ap-northeast-3 - AWSApiGatewayRestApi
 with error: AccessDeniedException:
	status code: 403, request id: 85eb4970-5cb8-4420-aaeb-cadfadacf600
1: failed job ap-northeast-3 - AWSDMSReplicationSubnetGroup
 with error: exceeded maximum number of attempts, 3, request send failed, Post "https://dms.ap-northeast-3.amazonaws.com/": dial tcp 13.248.4.179:443: i/o timeout
3: failed job ap-northeast-3 - AWSDMSReplicationInstance
 with error: exceeded maximum number of attempts, 3, request send failed, Post "https://dms.ap-northeast-3.amazonaws.com/": dial tcp 13.248.4.179:443: i/o timeout
9: failed job ap-northeast-3 - AWSDMSEndpoint
 with error: exceeded maximum number of attempts, 3, request send failed, Post "https://dms.ap-northeast-3.amazonaws.com/": dial tcp 13.248.4.179:443: i/o timeout
5: failed job ap-northeast-3 - AWSDMSReplicationTask
 with error: exceeded maximum number of attempts, 3, request send failed, Post "https://dms.ap-northeast-3.amazonaws.com/": dial tcp 13.248.4.179:443: i/o timeout
```

**Comment by jcarter3** [comment]
These should be fixed in the latest release. Thanks!
